import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { MyState } from "@/ContextApi/ContextApi";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "School management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer />
        <MyState>
          {children}
        </MyState>
      </body>
    </html>
  );
}
